# Generated by Django 3.2.7 on 2021-09-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeMonName', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to='pokemonImages')),
                ('pokemontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokeMon.pokemontype')),
            ],
        ),
    ]
